name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      - name: Install dependencies
        run: go get .
      - name: Build for Linux
        run: go build -v ./...
      - name: Archive exec file
        uses: actions/upload-artifact@v4
        with:
          name: gristctl
          path: gristctl